"""Generate mcpfw policy YAML from agentspec findings."""

from __future__ import annotations
import yaml
from .model import Architecture, Finding


def emit_policy(arch: Architecture, findings: list[Finding]) -> str:
    rules = []

    # Collect dangerous tools and patterns from findings
    write_tools = set()
    exec_tools = set()
    external_tools = set()
    auto_approved_destructive = set()

    for agent in arch.agents:
        for tool in agent.tools:
            if tool.type == "write":
                write_tools.add(tool.name)
            elif tool.type == "execute":
                exec_tools.add(tool.name)
            elif tool.type == "external":
                external_tools.add(tool.name)
            if tool.auto_approved and tool.type in ("write", "execute"):
                auto_approved_destructive.add(tool.name)

    # Rule 1: Block sensitive paths for write tools
    if write_tools:
        rules.append({
            "name": "block_sensitive_paths",
            "action": "deny",
            "tools": sorted(write_tools),
            "when": {"arg_matches": {"path": [
                "~/.ssh/**", "~/.aws/**", "~/.bashrc", "~/.profile", "~/.zshrc",
                "~/.gitconfig", "/etc/**", "**/.env*", "**/.git/hooks/**",
            ]}},
            "message": "Write to sensitive path blocked",
        })

    # Rule 2: Block dangerous command patterns for exec tools
    if exec_tools:
        rules.append({
            "name": "block_dangerous_commands",
            "action": "deny",
            "tools": sorted(exec_tools),
            "when": {"arg_contains": {"command": [
                "rm -rf /", "chmod 777", "curl | bash", "wget | sh",
                "> /dev/sd", "mkfs", "dd if=",
            ]}},
            "message": "Dangerous command pattern blocked",
        })

    # Rule 3: Allow all read tools
    read_tools = sorted({t.name for a in arch.agents for t in a.tools if t.type == "read"})
    if read_tools:
        rules.append({
            "name": "allow_reads",
            "action": "allow",
            "tools": read_tools,
        })

    # Rule 4: Allow scoped write tools (those with non-* scope)
    for agent in arch.agents:
        for tool in agent.tools:
            if tool.type == "write" and tool.scope != "*":
                rules.append({
                    "name": f"allow_scoped_{tool.name}",
                    "action": "allow",
                    "tools": [tool.name],
                    "when": {"arg_matches": {"path": [f"{tool.scope}"]}},
                })

    # Rule 5: Rate limit
    total_tools = sum(len(a.tools) for a in arch.agents)
    if total_tools > 5:
        rules.append({
            "name": "rate_limit",
            "action": "rate_limit",
            "tools": ["*"],
            "rate": "60/minute",
        })

    # Rule 6: Ask for auto-approved destructive tools (the ones agentspec flagged)
    if auto_approved_destructive:
        rules.append({
            "name": "require_approval_destructive",
            "action": "ask",
            "tools": sorted(auto_approved_destructive),
            "message": "Destructive tool — was auto-approved, now requires human approval",
        })

    # Rule 7: Default — ask for anything unmatched
    rules.append({
        "name": "default_ask",
        "action": "ask",
        "tools": ["*"],
        "message": "Unrecognized tool call requires approval",
    })

    policy = {
        "name": f"{arch.name}-policy",
        "rules": rules,
    }

    # Add comments as a header
    header = (
        f"# mcpfw policy generated by agentspec\n"
        f"# Source: {arch.name}\n"
        f"# Agents: {len(arch.agents)}, Tools: {total_tools}, "
        f"Findings: {len(findings)}\n"
        f"# Review and customize before deploying.\n\n"
    )

    return header + yaml.dump(policy, default_flow_style=False, sort_keys=False)
