"""Generate runtime enforcement policies from agentspec findings."""

from __future__ import annotations
import json
import yaml
from .model import Architecture, Finding


def _extract_tool_sets(arch: Architecture):
    """Extract categorized tool sets from architecture."""
    write_tools, exec_tools, read_tools, auto_approved = set(), set(), set(), set()
    for agent in arch.agents:
        for tool in agent.tools:
            if tool.type == "write":
                write_tools.add(tool.name)
            elif tool.type == "execute":
                exec_tools.add(tool.name)
            elif tool.type == "read":
                read_tools.add(tool.name)
            if tool.auto_approved and tool.type in ("write", "execute"):
                auto_approved.add(tool.name)
    return sorted(write_tools), sorted(exec_tools), sorted(read_tools), sorted(auto_approved)


SENSITIVE_PATHS = [
    "~/.ssh/**", "~/.aws/**", "~/.bashrc", "~/.profile", "~/.zshrc",
    "~/.gitconfig", "/etc/**", "**/.env*", "**/.git/hooks/**",
]

DANGEROUS_COMMANDS = [
    "rm -rf /", "chmod 777", "curl | bash", "wget | sh",
    "> /dev/sd", "mkfs", "dd if=",
]


def _header(arch: Architecture, findings: list[Finding], fmt: str) -> str:
    total = sum(len(a.tools) for a in arch.agents)
    return (
        f"# Policy generated by agentspec (format: {fmt})\n"
        f"# Source: {arch.name}\n"
        f"# Agents: {len(arch.agents)}, Tools: {total}, Findings: {len(findings)}\n\n"
    )


# ── mcpfw (YAML) ──────────────────────────────────────────────────────────

def emit_mcpfw(arch: Architecture, findings: list[Finding]) -> str:
    write_tools, exec_tools, read_tools, auto_approved = _extract_tool_sets(arch)
    rules = []

    if write_tools:
        rules.append({"name": "block_sensitive_paths", "action": "deny",
                       "tools": write_tools,
                       "when": {"arg_matches": {"path": SENSITIVE_PATHS}},
                       "message": "Write to sensitive path blocked"})

    if exec_tools:
        rules.append({"name": "block_dangerous_commands", "action": "deny",
                       "tools": exec_tools,
                       "when": {"arg_contains": {"command": DANGEROUS_COMMANDS}},
                       "message": "Dangerous command pattern blocked"})

    if read_tools:
        rules.append({"name": "allow_reads", "action": "allow", "tools": read_tools})

    for agent in arch.agents:
        for tool in agent.tools:
            if tool.type == "write" and tool.scope != "*":
                rules.append({"name": f"allow_scoped_{tool.name}", "action": "allow",
                               "tools": [tool.name],
                               "when": {"arg_matches": {"path": [tool.scope]}}})

    total = sum(len(a.tools) for a in arch.agents)
    if total > 5:
        rules.append({"name": "rate_limit", "action": "rate_limit", "tools": ["*"], "rate": "60/minute"})

    if auto_approved:
        rules.append({"name": "require_approval_destructive", "action": "ask",
                       "tools": auto_approved,
                       "message": "Destructive tool — was auto-approved, now requires human approval"})

    rules.append({"name": "default_ask", "action": "ask", "tools": ["*"],
                   "message": "Unrecognized tool call requires approval"})

    policy = {"name": f"{arch.name}-policy", "rules": rules}
    return _header(arch, findings, "mcpfw") + yaml.dump(policy, default_flow_style=False, sort_keys=False)


# ── OPA Rego ───────────────────────────────────────────────────────────────

def emit_rego(arch: Architecture, findings: list[Finding]) -> str:
    write_tools, exec_tools, read_tools, auto_approved = _extract_tool_sets(arch)
    lines = [_header(arch, findings, "rego")]
    lines.append("package agentspec.policy\n")
    lines.append("import rego.v1\n")
    lines.append("default allow := false\n")

    # Allow reads
    if read_tools:
        tools_set = ", ".join(f'"{t}"' for t in read_tools)
        lines.append(f"allow if {{ input.tool.name in {{{tools_set}}} }}\n")

    # Deny sensitive paths
    if write_tools:
        lines.append("deny contains msg if {")
        lines.append(f"    input.tool.name in {{{', '.join(repr(t) for t in write_tools)}}}")
        lines.append("    sensitive_path(input.tool.arguments.path)")
        lines.append('    msg := "Write to sensitive path blocked"')
        lines.append("}\n")
        lines.append("sensitive_path(p) if startswith(p, \"~/.ssh\")")
        lines.append("sensitive_path(p) if startswith(p, \"~/.aws\")")
        lines.append("sensitive_path(p) if startswith(p, \"/etc/\")")
        lines.append("sensitive_path(p) if contains(p, \".env\")\n")

    # Deny dangerous commands
    if exec_tools:
        lines.append("deny contains msg if {")
        lines.append(f"    input.tool.name in {{{', '.join(repr(t) for t in exec_tools)}}}")
        lines.append("    dangerous_command(input.tool.arguments.command)")
        lines.append('    msg := "Dangerous command pattern blocked"')
        lines.append("}\n")
        for cmd in DANGEROUS_COMMANDS[:4]:
            lines.append(f'dangerous_command(c) if contains(c, "{cmd}")')
        lines.append("")

    # Require approval for auto-approved destructive
    if auto_approved:
        lines.append("require_approval if {")
        lines.append(f"    input.tool.name in {{{', '.join(repr(t) for t in auto_approved)}}}")
        lines.append("}\n")

    return "\n".join(lines)


# ── Cedar ──────────────────────────────────────────────────────────────────

def emit_cedar(arch: Architecture, findings: list[Finding]) -> str:
    write_tools, exec_tools, read_tools, auto_approved = _extract_tool_sets(arch)
    lines = [_header(arch, findings, "cedar")]

    # Allow reads
    for t in read_tools:
        lines.append(f'permit(principal, action == Action::"invoke", resource == Tool::"{t}");')
    if read_tools:
        lines.append("")

    # Deny sensitive paths for write tools
    for t in write_tools:
        lines.append(f'forbid(principal, action == Action::"invoke", resource == Tool::"{t}")')
        lines.append(f"when {{ resource.path like \"~/.ssh/*\" || resource.path like \"~/.aws/*\" || resource.path like \"/etc/*\" }};")
    if write_tools:
        lines.append("")

    # Deny dangerous commands for exec tools
    for t in exec_tools:
        lines.append(f'forbid(principal, action == Action::"invoke", resource == Tool::"{t}")')
        lines.append(f'when {{ resource.command like "*rm -rf /*" || resource.command like "*curl | bash*" }};')
    if exec_tools:
        lines.append("")

    return "\n".join(lines)


# ── Microsoft Agent Governance Toolkit (YAML) ─────────────────────────────

def emit_agt(arch: Architecture, findings: list[Finding]) -> str:
    write_tools, exec_tools, read_tools, auto_approved = _extract_tool_sets(arch)
    rules = []

    if write_tools:
        rules.append({
            "name": "block_sensitive_paths",
            "action": "DENY",
            "conditions": [{"field": "tool.name", "operator": "in", "value": write_tools},
                           {"field": "tool.arguments.path", "operator": "matches_any",
                            "value": SENSITIVE_PATHS}],
            "message": "Write to sensitive path blocked",
            "owasp": "OWASP-AGENT-02",
        })

    if exec_tools:
        rules.append({
            "name": "block_dangerous_commands",
            "action": "DENY",
            "conditions": [{"field": "tool.name", "operator": "in", "value": exec_tools},
                           {"field": "tool.arguments.command", "operator": "contains_any",
                            "value": DANGEROUS_COMMANDS}],
            "message": "Dangerous command pattern blocked",
            "owasp": "OWASP-AGENT-02",
        })

    if auto_approved:
        rules.append({
            "name": "require_approval_destructive",
            "action": "HUMAN_APPROVAL",
            "conditions": [{"field": "tool.name", "operator": "in", "value": auto_approved}],
            "message": "Destructive tool requires human approval",
            "owasp": "OWASP-AGENT-08",
        })

    if read_tools:
        rules.append({"name": "allow_reads", "action": "ALLOW",
                       "conditions": [{"field": "tool.name", "operator": "in", "value": read_tools}]})

    rules.append({"name": "default_deny", "action": "DENY",
                   "conditions": [{"field": "tool.name", "operator": "exists"}],
                   "message": "Unrecognized tool call denied by default"})

    policy = {"apiVersion": "agent-governance/v1", "kind": "Policy",
              "metadata": {"name": f"{arch.name}-policy", "generatedBy": "agentspec"},
              "spec": {"rules": rules}}

    return _header(arch, findings, "agt") + yaml.dump(policy, default_flow_style=False, sort_keys=False)


# ── Dispatch ───────────────────────────────────────────────────────────────

EMITTERS = {
    "mcpfw": emit_mcpfw,
    "rego": emit_rego,
    "cedar": emit_cedar,
    "agt": emit_agt,
}

def emit_policy(arch: Architecture, findings: list[Finding], fmt: str = "mcpfw") -> str:
    emitter = EMITTERS.get(fmt)
    if not emitter:
        raise ValueError(f"Unknown policy format '{fmt}'. Choose from: {', '.join(EMITTERS)}")
    return emitter(arch, findings)
